/**
 * @file duffing_msws32.c
 * @author Ricardo Jorge Dias Sampaio
 * @brief Implements the functions needed for the key generator based on the Duffing Map and the MSWS32 generator. 
 * Implements the functions needed for the key generator based on the Duffing Map and the MSWS32 generator, including commentaries. 
 * @version 0.1
 * @date 2024-07-04
 * 
 * @copyright Copyright (c) 2024
 */

#include "duffing_msws32.h"

/**
 * @brief External definition for doubleToUint64Bits function.
 *
 * This external definition is provided to satisfy the linker in case
 * the function is not inlined at all call sites.
 */
extern inline void doubleToUint64Bits(uint64_t* result , double d);



/**
 * @brief External definition for duffing_map function.
 *
 * This external definition is provided to satisfy the linker in case
 * the function is not inlined at all call sites.
 */
extern inline void duffing_map(duffing_var_t* duffing_map_variables);


/**
 * @brief External definition for msws32 function.
 *
 * This external definition is provided to satisfy the linker in case
 * the function is not inlined at all call sites.
 */
extern inline uint32_t msws32(msws32_var_t *msws32_variables);

/**
 * @brief Initializes the Duffing map generator.
 * Initializes the Duffing map generator by performing a number of iterations, used to ensure that the transient less-chaotic component of the map is 'discarded', despite the high sensitivity to the initial conditions of the map performing some iterations will increase the chaoticity of the generated keys.
 * 
 * @param duffing_map_variables Pointer to the duffing_var_t structure containing the variables for the Duffing map.
 * @param iterations The number of iterations to perform.
 */
void initialize_generator(duffing_var_t* duffing_map_variables, const int iterations){
    for (int i = 0; i < iterations; i++){
        duffing_map(duffing_map_variables);
    }
    
}

/**
 * @brief Set up the key generator.
 * Initializes both Duffing maps and the MSWS32 input varibles, used in the setup of the program. Gets the key generator in a ready to use state.
 * 
 * @param duffing_map_1 Pointer to the first duffing_var_t structure for the Duffing map.
 * @param iterations1 The number of iterations for the first Duffing map.
 * @param duffing_map_2 Pointer to the second duffing_var_t structure for the Duffing map.
 * @param iterations2 The number of iterations for the second Duffing map.
 * @param msws32_variables Pointer to the msws32_var_t structure for the MSWS32 generator.
 */
void key_generator_setup(duffing_var_t* duffing_map_1, const int iterations1, 
                        duffing_var_t* duffing_map_2, const int iterations2,
                        msws32_var_t* msws32_variables){
    initialize_generator(duffing_map_1, iterations1);
    initialize_generator(duffing_map_2, iterations2);
    doubleToUint64Bits(&(msws32_variables->x),duffing_map_2->y);
    initialize_generator(duffing_map_2, iterations2);
    doubleToUint64Bits(&(msws32_variables->s),duffing_map_2->y);
}

/**
 * @brief Generates a new key using the Duffing map and MSWS32 generator.
 * Generates a new 32-bit key by performing one iteration of the Duffing map and the MSWS32 generator.
 * 
 * @param duffing_map_variables Pointer to the duffing_var_t structure containing the variables for the Duffing map.
 * @param msws32_variables Pointer to the msws32_var_t structure containing the variables for the MSWS32 generator.
 * @return uint32_t The new key generated by the Duffing map and MSWS32 generator.
 */
uint32_t key_generator(duffing_var_t* duffing_map_variables, msws32_var_t* msws32_variables) {
    duffing_map(duffing_map_variables);
    doubleToUint64Bits(&(msws32_variables->w) ,duffing_map_variables->y);
    return msws32(msws32_variables);
}